### ISSUE TITLE
systemd auto-start uses different config file 

### ISSUE THREAD

**Issue by gogreenpower** [filebrowser/docs#20]
My config file

`Sign up:          false
Create User Dir:  false
Auth method:      json
Shell:

Branding:
  Name:
  Files override:
  Disable external links:  false

Server:
  Log:           stdout
  Port:          9876
  Base URL:
  Root:          .
  Socket:
  Address:       192.168.1.2
  TLS Cert:
  TLS Key:
  Exec Enabled:  false

Defaults:
  Scope:      .
  Locale:     en
  View mode:  mosaic
  Commands:
  Sorting:
    By:
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": null
}
`

and the results of "systemctl status filebrowser"

`● filebrowser.service - Filebrowser
   Loaded: loaded (/etc/systemd/system/filebrowser.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-11-11 12:44:52 AWST; 6min ago
  Process: 5953 ExecStart=/usr/local/bin/filebrowser -c /etc/filebrowser/ -d /etc/filebrowser/.db (code=exited, status=1/FAILURE)
 Main PID: 5953 (code=exited, status=1/FAILURE)

Nov 11 12:44:52 Emby-Pi systemd[1]: Started Filebrowser.
Nov 11 12:44:52 Emby-Pi filebrowser[5953]: 2020/11/11 12:44:52 No config file used
Nov 11 12:44:52 Emby-Pi filebrowser[5953]: 2020/11/11 12:44:52 listen tcp 127.0.0.1:8080: bind: address already in use
Nov 11 12:44:52 Emby-Pi systemd[1]: filebrowser.service: Main process exited, code=exited, status=1/FAILURE
Nov 11 12:44:52 Emby-Pi systemd[1]: filebrowser.service: Failed with result 'exit-code'.
`

when manually run from the command line it works fine.

Any ideas?

**Comment by mckaygerhard** [comment]
is a sshistemd problem maybe reading the documentation of the unit files.. cos you said _when manually run from the command line it works fine._ so is not file browser problem. Sorry.

**Comment by mckaygerhard** [comment]
i will provide later a propert init.d sysvinit file and a openrc file for alpine and devuan, cos i not use systemd.. i will remain this open until i provide the Merge Request.

**Comment by mizzyexists** [comment]
Currently having an issue with Systemd as well and have just discovered that it is being blocked by SELinux. Gonna see try and investigate how to allow it.
