### ISSUE TITLE
commands dont work on windows.

### ISSUE THREAD

**Issue by xreann20** [filebrowser/docs#6]
Usage:
  filebrowser serve [flags]
  filebrowser serve [command]

Aliases:
  serve, server

Available Commands:
  version     Print the version number of File Browser

Flags:
  -a, --address string             Address to listen to (default is all of them)
      --auth.header string         The header name used for proxy authentication (default "X-Forwarded-User")
      --auth.method string         Switch between 'none', 'default' and 'proxy' authentication (default "default")
  -b, --baseurl string             Base URL
  -d, --database string            Database file (default "./filebrowser.db")
      --defaults.allowCommands     Default allow commands option for new users (default true)
      --defaults.allowEdit         Default allow edit option for new users (default true)
      --defaults.allowNew          Default allow new option for new users (default true)
      --defaults.allowPublish      Default allow publish option for new users (default true)
      --defaults.commands string   Default commands option for new users (default "git svn hg")
      --defaults.locale string     Default locale for new users, set it empty to enable auto detect from browser
  -s, --defaults.scope string      Default scope option for new users (default ".")
      --defaults.viewMode string   Default view mode for new users (default "mosaic")
  -h, --help                       help for serve
  -l, --log string                 Errors logger; can use 'stdout', 'stderr' or file (default "stdout")
  -p, --port int                   HTTP Port (default is random)
      --prefixurl string           Prefix URL
      --recaptcha.host string      Use another host for ReCAPTCHA. recaptcha.net might be useful in China (default "https://www.google.com")
      --recaptcha.key string       ReCaptcha site key
      --recaptcha.secret string    ReCaptcha secret
      --staticgen string           Static Generator you want to enable
      --version                    version for serve

Global Flags:
  -c, --config string   config file (defaults are './.filebrowser[ext]', '$HOME/.filebrowser[ext]' or '/etc/filebrowser/.filebrowser[ext]')

Use "filebrowser serve [command] --help" for more information about a command.

panic: unknown command "rm" for "filebrowser serve"

goroutine 1 [running]:
github.com/filebrowser/filebrowser/cli/cmd.Execute()
        /src/cli/cmd/root.go:37 +0x66
main.main()
        /src/cli/main.go:6 +0x27

C:\Program Files\filebrowser>./.filebrowser
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by hacdias** [comment]
@xreann20 you must be using an older version of File Browser. Those commands don't exist anymore. Please check the current [documentation](https://docs.filebrowser.xyz/cli).

Also, you need to run `.\filebrowser.exe` and not `./.filebrowser`. Please note the dot and the backslash.
